### PR TITLE
Add convertHexToByteArray.py

### PR DESCRIPTION
**Pull request by NicoHood**
A simple python script that can replace the mushclient with the lua script. It outputs nearly the same format. The ony difference is that `0x00` will be displayed as `0x0`.

Python is way faster and simpler to use on linux, so I hope this script helps. I have not tested every single combination, you might want to still have a closer look to it.

### CODE REVIEW

**Comment by NicoHood** [comment]
I've noticed that the script misses some lines with the xfce terminal on arch. Using xterm this does not happen. So you better use it with `convertHexToByteArray.py bootloader.hex > bootloader_Hex.c`

**Comment by nickgammon** [comment]
Your script misses the last line of the output. I suggest you need to print the final (unfilled) line. Also the sum check differs from what I get on the same file.

For example on the Lilypad bootloader I get:

    // MD5 sum = 27 EB 87 14 5D 45 D4 D8 41 44 52 CE 0A 2B 8C 5F 

And you get:

    // MD5 sum = 654f86b6aff0ce8a50e161bfa497f787

---

Also it generates an invalid variable name if you supply it with a path, eg.

    const uint8_t /home/nick/Development/arduino-1.6.9/hardware/arduino/avr/bootloaders/atmega/ATmegaBOOT_168_atmega328_pro_8MHz_hex [] PROGMEM = {

**Comment by nickgammon** [comment]
If you fix those things it looks nice and short. :) You might want to mention the need to get the IntelHex library (and how to do that).

**Comment by NicoHood** [comment]
Alright. Do you calculate the md5 over the input hex file or over the output converted data? I calculated it for the hex file, that might be the problem.

You said it misses the last line of the output, can you give me a sample hexfile to test that?

**Comment by nickgammon** [comment]
```
// File = /home/nick/Development/arduino-1.6.9/hardware/arduino/avr/bootloaders/atmega/ATmegaBOOT_168_atmega328_pro_8MHz.hex
// Loader start: 0x7800 length 1932
// MD5 sum = 654f86b6aff0ce8a50e161bfa497f787

const uint8_t /home/nick/Development/arduino-1.6.9/hardware/arduino/avr/bootloaders/atmega/ATmegaBOOT_168_atmega328_pro_8MHz_hex [] PROGMEM = {
0x0C, 0x94, 0x34, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C,
0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C,
...
0xC7, 0xCF, 0x10, 0x30, 0x11, 0xF0, 0x02, 0x96, 0xE5, 0xCF, 0x11, 0x24, 0x80, 0x91, 0xC0, 0x00,
0x85, 0xFF, 0xC5, 0xCE, 0xC8, 0xCE, 0x8E, 0xE1, 0x0E, 0x94, 0xC7, 0x3C, 0xAE, 0xCD, 0x85, 0xE9,
}; // end of /home/nick/Development/arduino-1.6.9/hardware/arduino/avr/bootloaders/atmega/ATmegaBOOT_168_atmega328_pro_8MHz_hex
```

Compared to my output:

```
// File =  ATmegaBOOT_168_atmega328_pro_8MHz.hex
// Loader start: 7800, length: 2048
// MD5 sum = 27 EB 87 14 5D 45 D4 D8 41 44 52 CE 0A 2B 8C 5F 

const byte ATmegaBOOT_168_atmega328_pro_8MHz_hex [] PROGMEM = {
0x0C, 0x94, 0x34, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 
0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 0x0C, 0x94, 0x51, 0x3C, 
...
0xC7, 0xCF, 0x10, 0x30, 0x11, 0xF0, 0x02, 0x96, 0xE5, 0xCF, 0x11, 0x24, 0x80, 0x91, 0xC0, 0x00, 
0x85, 0xFF, 0xC5, 0xCE, 0xC8, 0xCE, 0x8E, 0xE1, 0x0E, 0x94, 0xC7, 0x3C, 0xAE, 0xCD, 0x85, 0xE9, 
0x0E, 0x94, 0xC7, 0x3C, 0xAA, 0xCD, 0xF8, 0x94, 0xFF, 0xCF, 0x80, 0x00,  
}; // end of ATmegaBOOT_168_atmega328_pro_8MHz_hex
```

That last line is missing from yours:

```
0x0E, 0x94, 0xC7, 0x3C, 0xAA, 0xCD, 0xF8, 0x94, 0xFF, 0xCF, 0x80, 0x00,  
```

---

> Do you calculate the md5 over the input hex file or over the output converted data?

I calculate it over the converted data because that is what I check in PROGMEM when calculating the sumcheck. The actual data in memory. It has to be filled out to the correct length (with 0xFF) because that is what will be in the processor PROGMEM.

**Comment by NicoHood** [comment]
I think I've covered all your notes and additionally found some other bugs that i've fixed. Please check again :)

Thanks for the feedback :)

**Pull request merged**
